[project]
name = "asteroids"
version = "0.1.0"
description = "A classical asteroid game created using Pygame library"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pygame==2.6.1",
]
